### ISSUE TITLE
Custom Handlebars missing

### ISSUE THREAD

**Issue by HavocsCall** [MostTornBrain/pf2e-md-exporter#17]
This probably isn't an issue with the module, but with me. I am still pretty new to Foundry module making and handlebars.

I made a new folder/module for Foundry that has my custom handlebars, but when I got to change the handlebar in the pf2e-exporter settings, it shows the folder, but no handlebar files inside.

![image](https://github.com/user-attachments/assets/b1a16a3d-78f3-4dbb-9b50-ca15257b4180)

I'm sure it's something small I am missing, but a nudge in the right direction would be appreciated.

**Comment by MostTornBrain** [comment]
The Foundry file chooser GUI will only show certain types of files.  Unfortunately, handlebar files are hidden.   So, you have to cut and paste the paths to the handlebars you want.  You can't use the GUI to select them.  This is a Foundry restriction with how they implemented the GUI for choosing files.

**Comment by HavocsCall** [comment]
Gotcha, I will do that. Thank you.
