### ISSUE TITLE
Loot actors fail to export properly

### ISSUE THREAD

**Issue by MostTornBrain** [MostTornBrain/pf2e-md-exporter#18]
Looks like I need to create a loot handlebar.  Right now it is using the monster handlebar by default which assumes certain atttributes exist and since this is a "loot" type actor it is missing the normal monster information the handlerbar expects, so under V11 it generates an invalid statblock and in V12 it blows up the whole export.

**Comment by MostTornBrain** [comment]
v0.9.17 is a rough first pass at supporting loot actors.    A future update will make it a bit better looking.

**Comment by scooper4711** [comment]
side note - beginner box, dragon's lair loot contains an emerald worth 20gp. The value is lost in the export.

**Comment by MostTornBrain** [comment]
> side note - beginner box, dragon's lair loot contains an emerald worth 20gp. The value is lost in the export.

Yes, that is part of the enhancements I plan to make.  I plan to make it as a table with the value listed, similar to how it appears in Foundry.

**Comment by MostTornBrain** [comment]
I finally had some time to look at this.   I think this is more usable now:   
![image](https://github.com/user-attachments/assets/b1192f50-5013-4b83-b6ec-9258bb344b58)
I'll push this update with a few other changes hopefully tonight.

**Comment by scooper4711** [comment]
Oh - that looks great!

**Comment by MostTornBrain** [comment]
v0.9.20 implements this change.
