### ISSUE TITLE
Not exporting actor skill bonuses

### ISSUE THREAD

**Issue by PizzaPenguinn** [MostTornBrain/pf2e-md-exporter#19]
Might be due to More Handlebar Helpers not being completely up to date, but it seems like the exporter is currently not including the skill bonuses of any Actors for me.

<img width="307" alt="image" src="https://github.com/user-attachments/assets/a7a500bb-ea9f-4138-8057-d790a347352f">

**Comment by MostTornBrain** [comment]
Thanks for the report!    It looks like 2 months ago Foundry changed the way skills are formatted in the json data.  I need to update the monster handlebar to parse the new format properly.

**Comment by MostTornBrain** [comment]
v0.9.16 fixes this issue.
