### ISSUE TITLE
pf2e-spells.css in dark theme

### ISSUE THREAD

**Issue by Drakshasak** [MostTornBrain/pf2e-md-exporter#2]
The snippet for spells looks bad when you run obsidian in dark theme. Any chance for an alternate snippet style for a dark theme? 
![Screenshot 2024-03-26 170149](https://github.com/MostTornBrain/pf2e-md-exporter/assets/30575514/1c9dd781-98fe-48f4-8d8f-4bf4278c2cd9)

**Comment by MostTornBrain** [comment]
I'll look into what I need to change to address this.   Thanks for the feedback.

**Comment by MostTornBrain** [comment]
I updated the CSS to better handle dark-mode.
