### ISSUE TITLE
Handlebar options for journal pages

### ISSUE THREAD

**Issue by HavocsCall** [MostTornBrain/pf2e-md-exporter#20]
I don't see a way to change the handlebar for journal pages, but there has to be a one, right? Even if there isn't a default handlebar, is there a way to add the functionality to manually add one?

Thanks for all your work on this, it has made my GM life easier.

**Comment by MostTornBrain** [comment]
Journal pages are special as they are neither an item nor an actor and are mostly just HTML that gets converted to the equivalent Markdown via javascript functions in the module.   This is functionality that was inherited from the original Markdown Exporter modules written by Farling42. 

Unfortunately, if you want to customize how journal pages are rendered, you will need to edit the javascript source code directly, specifically found in the file `export-markdown.js`.

**Comment by HavocsCall** [comment]
Does that include the obsidian frontmatter?

**Comment by MostTornBrain** [comment]
Yes, it is done by this function in `export-markdown.js`:

```js
function frontmatter(doc, showheader=true) {
    let header = showheader ? `\n# ${doc.name}\n` : "";
    return FRONTMATTER + 
        `title: "${doc.name}"\n` + 
        `icon: "${DOCUMENT_ICON.lookup(doc)}"\n` +
        `aliases: "${doc.name}"\n` + 
        `foundryId: ${doc.uuid}\n` + 
        `tags:\n  - ${doc.documentName}\n` +
        FRONTMATTER +
        header;
}
```

**Comment by HavocsCall** [comment]
Got it, I will try it. Thank you
