### ISSUE TITLE
Idea: Note Type Tags

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [MostTornBrain/pf2e-md-exporter#21]
Might be useful to add the Type of note as a tag. 

Example: 

tags:
{{#each system.traits.value as |trait|}}
  - {{trait}}
{{/each}}
  - pf2eHazard
{{#if system.details.isComplex}}  - complex{{/if}}
{{#if system.details.publication.remaster}}
  - remaster
{{/if~}}

This is the hazards template. I've added the pf2eHazard tag. 
Useful for things like Meta Bind. eg:

`INPUT[suggester(optionQuery(#pf2eHazard"))]`

Now you can have a template that lets you select a hazard from the list of hazards. 
Just helps expand the notes to be usable in more ways. We have this already as a Property, but having it as a Tag means it's able to be used in whatever way the user needs.

**Comment by MostTornBrain** [comment]
Thank you for the suggestion.   I'll incorporate this in an upcoming update.

**Comment by MostTornBrain** [comment]
> We have this already as a Property, but having it as a Tag means it's able to be used in whatever way the user needs.

If the note type is added as a tag, would you recommend it be removed as a property so it is listed solely as a tag?

**Comment by ObsidianTTRPGProject** [comment]
Honestly I would leave both. They are both useful for different things. Some people prefer properties while others lean towards tags

**Comment by MostTornBrain** [comment]
v0.9.20 implements this change
