### ISSUE TITLE
Updated Hazard Handlebar

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [MostTornBrain/pf2e-md-exporter#5]
Have updated the Handlebar with some changes following a deeper audit tonight. 

- These are now working with Initiative Tracker. 
- Added ac: value
- Added Property: statblock: inline
- Added Property for 'Force Note View Mode' Plugin: obsidianUIMode: preview
- Added Trait for Complex Traps (note: I added it as trait_06 because I have no idea how to make it work with the intelligent index that the rest of the traits are using). 
- Upon review of Stealth DC # across basic and complex traps discovered that the calculation differs for both. 
- Thus updated to:   - name: "Stealth DC {{#if system.details.isComplex}}{{system.attributes.stealth.value}}{{else}}{{add system.attributes.stealth.value 10}}{{/if}}" 
- Normal Trap = Stealth+10
- Complex Trap = Stealth

Note: By default Traps dont display AC; Fort; Ref; Will. I didnt do anything about this though as it doesnt do any harm and there are hazards that do display this info. 

Note2: Raw statblocks do not display: Immunities object immunities. Foundry does display this though. Did not do anything about this since its coming from the source (Foundry).

[hazard_handlebar_complex.zip](https://github.com/MostTornBrain/pf2e-md-exporter/files/14834532/hazard_handlebar_complex.zip)

**Comment by MostTornBrain** [comment]
I have included these changes in the v0.7.2 release.    I also made one minor addition so the Hazard statblocks support the preference of whether to include markdown for Initiative Tracker.
