### ISSUE TITLE
Does not work with Foundry 12.

### ISSUE THREAD

**Issue by CCHiggins** [MostTornBrain/pf2e-md-exporter#6]
Settings and export do not show up with Foundry V12.

**Comment by MostTornBrain** [comment]
Thanks for the heads up.    After an initial investigation, it appears there are several issues with v12 compatibility.   I'm working through them as my time permits.

**Comment by MostTornBrain** [comment]
I made a V12 compatible version of the module, however the changes are not backwards compatible with V11.   I created a new branch for V12 support that can be installed via this new V12-specific manifest link:   https://raw.githubusercontent.com/MostTornBrain/pf2e-md-exporter/feature/v12-support/moduleV12.json

If you see any other oddities, feel free to let me know.

**Comment by MostTornBrain** [comment]
As of v0.9.8, both V11 and V12 are supported by the same standard module.    If you had been using the interim V12 beta fix module I linked to above, you will need to delete that module from your Foundry install and re-install the standard one.
This is the manifest for the standard module:   
`https://github.com/MostTornBrain/pf2e-md-exporter/releases/latest/download/module.json`
