### ISSUE TITLE
Bug: Journal image attachments exported as broken webp images

### ISSUE THREAD

**Issue by scooper4711** [MostTornBrain/pf2e-md-exporter#9]
Journal attachment images for Handouts all come out as 16 byte broken webp images. 

This is with both exporting both Cult of Cinders and Tomorrow Must Burn.

The non-forked md exporter exports the images just fine, but with a different naming convention.

**Comment by MostTornBrain** [comment]
Can you describe how you are exporting these?   I want to make sure I'm reproducing the same issue.   I do not own either of those modules, but assume it should happen with other modules as well.

**Comment by scooper4711** [comment]
1. I used the PDF Importer https://github.com/fryguy1013/pdftofoundry/
2. I click on the Journal tab
3. I select the folder for the adventure path
4. I right click on the folder and select "Export to Markdown"

**Comment by MostTornBrain** [comment]
So something like this?
![image](https://github.com/MostTornBrain/pf2e-md-exporter/assets/15065999/a1ed9b5b-901f-478d-ad96-4b3b95070f3e)

This appears to export fine, including webp images:
![image](https://github.com/MostTornBrain/pf2e-md-exporter/assets/15065999/79322ce6-4d9b-41f8-9639-c67eaa63cdb3)

I'll check to see if I have any PDFs from Paizon I can import.  Maybe it is something specific to how things are created in Foundry as part of the PDF import process...

**Comment by MostTornBrain** [comment]
Are you sure the pdf-to-foundry import process is creating the journal entry images correctly?   I have tried several Paizo PDFs I own and a few of them after importing will contain broken webp images (of size 16 bytes) within Foundry itself specifically for some of the handout entries.    This does not appear to be a PF2E Exporter issue - the source data the PDF import is creating appears to be incorrect in some instances.   I see this issue with Fall of Plaguestone and Troubles in Otari as two examples:  
![image](https://github.com/MostTornBrain/pf2e-md-exporter/assets/15065999/008a889a-45cc-4c60-8d16-e6928c54be62)

**Comment by scooper4711** [comment]
You nailed it. 

Last time I did this (when the images worked), I believe I was on Foundry V10. With your new plugin, I'm re-doing everything and sure enough, those hand-out images are broken.

Closing this.
